# Generated by Django 5.0.6 on 2024-05-21 16:53

import datetime
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drive_News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='El-nomrous', max_length=30, null=True, verbose_name='school name')),
                ('user_img', models.ImageField(upload_to='news_area/')),
                ('added_in', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Drive_News',
                'verbose_name_plural': 'Drive_News',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Mark_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='BYD', max_length=15, verbose_name='mark name')),
                ('m_logo', models.ImageField(default='byd.jpg', upload_to='marks')),
                ('country_made', models.CharField(choices=[('AF', 'Afghanistan'), ('AX', 'Åland Islands'), ('AL', 'Albania'), ('DZ', 'Algeria'), ('AS', 'American Samoa'), ('AD', 'Andorra'), ('AO', 'Angola'), ('AI', 'Anguilla'), ('AQ', 'Antarctica'), ('AG', 'Antigua and Barbuda'), ('AR', 'Argentina'), ('AM', 'Armenia'), ('AW', 'Aruba'), ('AU', 'Australia'), ('AT', 'Austria'), ('AZ', 'Azerbaijan'), ('BS', 'Bahamas'), ('BH', 'Bahrain'), ('BD', 'Bangladesh'), ('BB', 'Barbados'), ('BY', 'Belarus'), ('BE', 'Belgium'), ('BZ', 'Belize'), ('BJ', 'Benin'), ('BM', 'Bermuda'), ('BT', 'Bhutan'), ('BO', 'Bolivia'), ('BQ', 'Bonaire, Sint Eustatius and Saba'), ('BA', 'Bosnia and Herzegovina'), ('BW', 'Botswana'), ('BV', 'Bouvet Island'), ('BR', 'Brazil'), ('IO', 'British Indian Ocean Territory'), ('BN', 'Brunei'), ('BG', 'Bulgaria'), ('BF', 'Burkina Faso'), ('BI', 'Burundi'), ('CV', 'Cabo Verde'), ('KH', 'Cambodia'), ('CM', 'Cameroon'), ('CA', 'Canada'), ('KY', 'Cayman Islands'), ('CF', 'Central African Republic'), ('TD', 'Chad'), ('CL', 'Chile'), ('CN', 'China'), ('CX', 'Christmas Island'), ('CC', 'Cocos (Keeling) Islands'), ('CO', 'Colombia'), ('KM', 'Comoros'), ('CG', 'Congo'), ('CD', 'Congo (the Democratic Republic of the)'), ('CK', 'Cook Islands'), ('CR', 'Costa Rica'), ('CI', "Côte d'Ivoire"), ('HR', 'Croatia'), ('CU', 'Cuba'), ('CW', 'Curaçao'), ('CY', 'Cyprus'), ('CZ', 'Czechia'), ('DK', 'Denmark'), ('DJ', 'Djibouti'), ('DM', 'Dominica'), ('DO', 'Dominican Republic'), ('EC', 'Ecuador'), ('EG', 'Egypt'), ('SV', 'El Salvador'), ('GQ', 'Equatorial Guinea'), ('ER', 'Eritrea'), ('EE', 'Estonia'), ('SZ', 'Eswatini'), ('ET', 'Ethiopia'), ('FK', 'Falkland Islands (Malvinas)'), ('FO', 'Faroe Islands'), ('FJ', 'Fiji'), ('FI', 'Finland'), ('FR', 'France'), ('GF', 'French Guiana'), ('PF', 'French Polynesia'), ('TF', 'French Southern Territories'), ('GA', 'Gabon'), ('GM', 'Gambia'), ('GE', 'Georgia'), ('DE', 'Germany'), ('GH', 'Ghana'), ('GI', 'Gibraltar'), ('GR', 'Greece'), ('GL', 'Greenland'), ('GD', 'Grenada'), ('GP', 'Guadeloupe'), ('GU', 'Guam'), ('GT', 'Guatemala'), ('GG', 'Guernsey'), ('GN', 'Guinea'), ('GW', 'Guinea-Bissau'), ('GY', 'Guyana'), ('HT', 'Haiti'), ('HM', 'Heard Island and McDonald Islands'), ('VA', 'Holy See'), ('HN', 'Honduras'), ('HK', 'Hong Kong'), ('HU', 'Hungary'), ('IS', 'Iceland'), ('IN', 'India'), ('ID', 'Indonesia'), ('IR', 'Iran'), ('IQ', 'Iraq'), ('IE', 'Ireland'), ('IM', 'Isle of Man'), ('IL', 'Israel'), ('IT', 'Italy'), ('JM', 'Jamaica'), ('JP', 'Japan'), ('JE', 'Jersey'), ('JO', 'Jordan'), ('KZ', 'Kazakhstan'), ('KE', 'Kenya'), ('KI', 'Kiribati'), ('KW', 'Kuwait'), ('KG', 'Kyrgyzstan'), ('LA', 'Laos'), ('LV', 'Latvia'), ('LB', 'Lebanon'), ('LS', 'Lesotho'), ('LR', 'Liberia'), ('LY', 'Libya'), ('LI', 'Liechtenstein'), ('LT', 'Lithuania'), ('LU', 'Luxembourg'), ('MO', 'Macao'), ('MG', 'Madagascar'), ('MW', 'Malawi'), ('MY', 'Malaysia'), ('MV', 'Maldives'), ('ML', 'Mali'), ('MT', 'Malta'), ('MH', 'Marshall Islands'), ('MQ', 'Martinique'), ('MR', 'Mauritania'), ('MU', 'Mauritius'), ('YT', 'Mayotte'), ('MX', 'Mexico'), ('FM', 'Micronesia (Federated States of)'), ('MD', 'Moldova'), ('MC', 'Monaco'), ('MN', 'Mongolia'), ('ME', 'Montenegro'), ('MS', 'Montserrat'), ('MA', 'Morocco'), ('MZ', 'Mozambique'), ('MM', 'Myanmar'), ('NA', 'Namibia'), ('NR', 'Nauru'), ('NP', 'Nepal'), ('NL', 'Netherlands'), ('NC', 'New Caledonia'), ('NZ', 'New Zealand'), ('NI', 'Nicaragua'), ('NE', 'Niger'), ('NG', 'Nigeria'), ('NU', 'Niue'), ('NF', 'Norfolk Island'), ('KP', 'North Korea'), ('MK', 'North Macedonia'), ('MP', 'Northern Mariana Islands'), ('NO', 'Norway'), ('OM', 'Oman'), ('PK', 'Pakistan'), ('PW', 'Palau'), ('PS', 'Palestine, State of'), ('PA', 'Panama'), ('PG', 'Papua New Guinea'), ('PY', 'Paraguay'), ('PE', 'Peru'), ('PH', 'Philippines'), ('PN', 'Pitcairn'), ('PL', 'Poland'), ('PT', 'Portugal'), ('PR', 'Puerto Rico'), ('QA', 'Qatar'), ('RE', 'Réunion'), ('RO', 'Romania'), ('RU', 'Russia'), ('RW', 'Rwanda'), ('BL', 'Saint Barthélemy'), ('SH', 'Saint Helena, Ascension and Tristan da Cunha'), ('KN', 'Saint Kitts and Nevis'), ('LC', 'Saint Lucia'), ('MF', 'Saint Martin (French part)'), ('PM', 'Saint Pierre and Miquelon'), ('VC', 'Saint Vincent and the Grenadines'), ('WS', 'Samoa'), ('SM', 'San Marino'), ('ST', 'Sao Tome and Principe'), ('SA', 'Saudi Arabia'), ('SN', 'Senegal'), ('RS', 'Serbia'), ('SC', 'Seychelles'), ('SL', 'Sierra Leone'), ('SG', 'Singapore'), ('SX', 'Sint Maarten (Dutch part)'), ('SK', 'Slovakia'), ('SI', 'Slovenia'), ('SB', 'Solomon Islands'), ('SO', 'Somalia'), ('ZA', 'South Africa'), ('GS', 'South Georgia and the South Sandwich Islands'), ('KR', 'South Korea'), ('SS', 'South Sudan'), ('ES', 'Spain'), ('LK', 'Sri Lanka'), ('SD', 'Sudan'), ('SR', 'Suriname'), ('SJ', 'Svalbard and Jan Mayen'), ('SE', 'Sweden'), ('CH', 'Switzerland'), ('SY', 'Syria'), ('TW', 'Taiwan'), ('TJ', 'Tajikistan'), ('TZ', 'Tanzania'), ('TH', 'Thailand'), ('TL', 'Timor-Leste'), ('TG', 'Togo'), ('TK', 'Tokelau'), ('TO', 'Tonga'), ('TT', 'Trinidad and Tobago'), ('TN', 'Tunisia'), ('TR', 'Türkiye'), ('TM', 'Turkmenistan'), ('TC', 'Turks and Caicos Islands'), ('TV', 'Tuvalu'), ('UG', 'Uganda'), ('UA', 'Ukraine'), ('AE', 'United Arab Emirates'), ('GB', 'United Kingdom'), ('UM', 'United States Minor Outlying Islands'), ('US', 'United States of America'), ('UY', 'Uruguay'), ('UZ', 'Uzbekistan'), ('VU', 'Vanuatu'), ('VE', 'Venezuela'), ('VN', 'Vietnam'), ('VG', 'Virgin Islands (British)'), ('VI', 'Virgin Islands (U.S.)'), ('WF', 'Wallis and Futuna'), ('EH', 'Western Sahara'), ('YE', 'Yemen'), ('ZM', 'Zambia'), ('ZW', 'Zimbabwe'), (None, 'Select Country')], max_length=50, null=True)),
                ('bio', models.TextField(blank=True, default='\nProvident nihil minus qui consequatur non omnis maiores. Eos accusantium minus dolores iure perferendis tempore et consequatur.\n                   \n', null=True)),
            ],
            options={
                'verbose_name': 'Mark_model',
                'verbose_name_plural': 'Mark_models',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Advertise_action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_posts_adv_x', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Advertise_action',
                'verbose_name_plural': 'Advertise_action',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Decorator_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='bulb funy', max_length=15, verbose_name='deco name')),
                ('type', models.CharField(choices=[('داخلية', 'داخلية'), ('خارجية', 'خارجية'), ('اكسسوار', 'اكسسوار')], default=('اكسسوار', 'اكسسوار'), max_length=13, verbose_name='النوع')),
                ('part_img', models.ImageField(blank=True, default='decorators/car_decorations_5.jpg', null=True, upload_to='decorators')),
                ('price', models.DecimalField(decimal_places=2, default=250, max_digits=10, verbose_name='price(EGP)')),
                ('bio', models.TextField(blank=True, default='\nProvident nihil minus qui consequatur non omnis maiores. Eos accusantium minus dolores iure perferendis tempore et consequatur.\n                   \n', null=True, verbose_name='the bio')),
                ('added_in', models.DateTimeField(auto_now_add=True)),
                ('owned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_has_deco_part_x', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Decorator_model',
                'verbose_name_plural': 'Decorator_model',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Car_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Ze_1', max_length=15, verbose_name='mark name')),
                ('date_of_made', models.DateField(default=datetime.date(2022, 1, 5), verbose_name='date of Model')),
                ('m_img', models.ImageField(default='car_11.jpg', upload_to='marks_models/')),
                ('speed_km', models.PositiveIntegerField(default=120, verbose_name='speed with (KM)')),
                ('engine_capacity', models.DecimalField(decimal_places=2, default=3.5, max_digits=3, verbose_name='engine capacity (CC)')),
                ('weight', models.DecimalField(decimal_places=2, default=5.5, max_digits=3, verbose_name='car weight(TON)')),
                ('price', models.DecimalField(decimal_places=2, default=250000, max_digits=10, verbose_name='price(EGP)')),
                ('bio', models.TextField(blank=True, default='\nProvident nihil minus qui consequatur non omnis maiores. Eos accusantium minus dolores iure perferendis tempore et consequatur.\n                   \n', null=True)),
                ('family_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_of', to='core.mark_model')),
            ],
            options={
                'verbose_name': 'Car_model',
                'verbose_name_plural': 'Car_model',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Part_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Cylinder', max_length=15, verbose_name='mark name')),
                ('part_img', models.ImageField(default='car_part3.png', upload_to='marks')),
                ('price', models.DecimalField(decimal_places=2, default=1250, max_digits=10, verbose_name='price(EGP)')),
                ('bio', models.TextField(blank=True, default='\nProvident nihil minus qui consequatur non omnis maiores. Eos accusantium minus dolores iure perferendis tempore et consequatur.\n                   \n', null=True)),
                ('added_in', models.DateTimeField(auto_now_add=True)),
                ('belong_to_mark', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a_part_from_mark_x', to='core.mark_model')),
                ('belong_to_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a_part_from_model_y', to='core.car_model')),
                ('owned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_has_part_x', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Part_model',
                'verbose_name_plural': 'Part_model',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Petrol_area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_branch', models.URLField(default='https://maps.app.goo.gl/Ba5yubWZUc811PVg7')),
                ('address', models.CharField(blank=True, default='م33محل الغربالي', max_length=40, null=True, verbose_name='العنوان')),
                ('name', models.CharField(blank=True, default='Petrojet EGY', max_length=30, null=True, verbose_name='petrol name')),
                ('f95', models.DecimalField(decimal_places=2, default=100.51, max_digits=10, verbose_name='f95 obtained(LE):')),
                ('f95_cost', models.DecimalField(decimal_places=2, default=250, max_digits=10, verbose_name='f95 price(EGP)')),
                ('f92', models.DecimalField(decimal_places=2, default=25.2, max_digits=10, verbose_name='f92 obtained(LE):')),
                ('f92_cost', models.DecimalField(decimal_places=2, default=250, max_digits=10, verbose_name='f92 price(EGP)')),
                ('f90', models.DecimalField(decimal_places=2, default=300.5, max_digits=10, verbose_name='f90 obtained(LE):')),
                ('f90_cost', models.DecimalField(decimal_places=2, default=250, max_digits=10, verbose_name='f90 price(EGP)')),
                ('f80', models.DecimalField(decimal_places=2, default=50.6, max_digits=10, verbose_name='f80 obtained(LE):')),
                ('f80_cost', models.DecimalField(decimal_places=2, default=250, max_digits=10, verbose_name='f80 price(EGP)')),
                ('owned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_has_petrol_x', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Petrol_area',
                'verbose_name_plural': 'Petrol_area',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='School_of_drive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='El-nomrous Driving', max_length=30, null=True, verbose_name='school name')),
                ('bio', models.TextField(blank=True, default='\nProvident nihil minus qui consequatur non omnis maiores. Eos accusantium minus dolores iure perferendis tempore et consequatur.\n                   \n', null=True, verbose_name='info')),
                ('added_in', models.DateTimeField(auto_now_add=True)),
                ('owned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_has_school_x', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'School of drive',
                'verbose_name_plural': 'School of drive',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Eltyyar Cars', max_length=40, null=True, verbose_name='اسم المحل')),
                ('address', models.CharField(blank=True, default='م33محل الغربالي', max_length=40, null=True, verbose_name='العنوان')),
                ('user_img', models.ImageField(default='car_part2.png', upload_to='user_named')),
                ('profile_activity', models.CharField(choices=[('وكيل ماركة', 'وكيل ماركة'), ('مركز صيانة', 'مركز صيانة'), ('محل قطع غيار', 'محل قطع غيار'), ('إيجار', 'إيجار'), ('وقود', 'وقود'), ('شراء', 'شراء'), ('بيع-إيجار-شراء', 'بيع-إيجار-شراء'), ('أكسسوارت', 'أكسسوارت'), ('مركز تدريب', 'مركز تدريب')], default=('بيع-إيجار-شراء', 'بيع-إيجار-شراء'), max_length=23, verbose_name='نوع النشاط')),
                ('user_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('location_branch', models.URLField(default='https://maps.app.goo.gl/Ba5yubWZUc811PVg7')),
                ('user_of', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='r_has_profile_x', to=settings.AUTH_USER_MODEL, verbose_name='for user')),
            ],
            options={
                'verbose_name': 'User_model',
                'verbose_name_plural': 'User_model',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
