# Generated by Django 5.0.6 on 2024-05-21 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_part_model_owned_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='advertise_action',
            name='adv_poster',
            field=models.ImageField(default='byd.jpg', upload_to='adv_poster'),
        ),
        migrations.AddField(
            model_name='advertise_action',
            name='bio',
            field=models.TextField(blank=True, default='\nProvident nihil minus qui consequatur non omnis maiores. Eos accusantium minus dolores iure perferendis tempore et consequatur.\n                   \n', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='advertise_action',
            name='name',
            field=models.CharField(default='BYD', max_length=55, verbose_name='mark name'),
        ),
        migrations.AddField(
            model_name='advertise_action',
            name='posted_in',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='advertise_action',
            name='post_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_posts_adv_x', to=settings.AUTH_USER_MODEL),
        ),
    ]
