# Generated by Django 5.0.6 on 2024-05-24 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_advertise_action_adv_poster_advertise_action_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark_model',
            name='cat_type_field',
            field=models.CharField(blank=True, default=('ماركة سيارات', 'ماركة سيارات'), max_length=15, null=True, verbose_name='نوع الماركة'),
        ),
        migrations.AlterField(
            model_name='advertise_action',
            name='adv_poster',
            field=models.ImageField(default='hire_1.jpg', upload_to='صوره الاعلان'),
        ),
        migrations.AlterField(
            model_name='advertise_action',
            name='bio',
            field=models.TextField(blank=True, default='\nProvident nihil minus qui consequatur non omnis maiores. Eos accusantium minus dolores iure perferendis tempore et consequatur.\n                   \n', max_length=150, null=True, verbose_name='التفاصبل'),
        ),
        migrations.AlterField(
            model_name='advertise_action',
            name='name',
            field=models.CharField(default='BYD', max_length=55, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='user_model',
            name='profile_activity',
            field=models.CharField(choices=[('وكيل ماركة', 'وكيل ماركة'), ('مركز صيانة', 'مركز صيانة'), ('محل قطع غيار', 'محل قطع غيار'), ('إيجار', 'إيجار'), ('وقود', 'وقود'), ('شراء', 'شراء'), ('بيع-إيجار-شراء', 'بيع-إيجار-شراء'), ('أكسسوارت', 'أكسسوارت'), ('مركز تدريب', 'مركز تدريب'), ('عميل', 'عميل')], default=('بيع-إيجار-شراء', 'بيع-إيجار-شراء'), max_length=23, verbose_name='نوع النشاط'),
        ),
    ]
