# Generated by Django 5.0.6 on 2024-05-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_mark_model_cat_type_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertise_action',
            name='adv_cost',
            field=models.DecimalField(decimal_places=2, default=1250, max_digits=10, verbose_name='سعر الأعلان\\الإيجار'),
        ),
        migrations.AddField(
            model_name='advertise_action',
            name='location_branch',
            field=models.URLField(blank=True, default='https://maps.app.goo.gl/Ba5yubWZUc811PVg7', null=True, verbose_name='رابط الأعلان'),
        ),
        migrations.AlterField(
            model_name='mark_model',
            name='cat_type_field',
            field=models.CharField(blank=True, choices=[('ماركة سيارات', 'ماركة سيارات'), ('قطع غيار', 'قطع غيار'), ('اكسسوار', 'اكسسوار')], default=('ماركة سيارات', 'ماركة سيارات'), max_length=15, null=True, verbose_name='نوع الماركة'),
        ),
        migrations.AlterField(
            model_name='user_model',
            name='profile_activity',
            field=models.CharField(choices=[('وكيل ماركة', 'وكيل ماركة'), ('مركز صيانة', 'مركز صيانة'), ('محل قطع غيار', 'محل قطع غيار'), ('إيجار', 'إيجار'), ('وقود', 'وقود'), ('بيع-إيجار-شراء', 'بيع-إيجار-شراء'), ('أكسسوارت', 'أكسسوارت'), ('مركز تدريب', 'مركز تدريب'), ('عميل', 'عميل')], default=('أكسسوارت', 'أكسسوارت'), max_length=23, verbose_name='نوع النشاط'),
        ),
    ]
