# Generated by Django 5.0.6 on 2024-05-29 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_advertise_action_adv_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_model',
            name='owned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='belongs_to', to='core.mark_model', verbose_name='من فئة'),
        ),
        migrations.AlterField(
            model_name='car_model',
            name='family_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_of', to='core.mark_model'),
        ),
        migrations.AlterField(
            model_name='car_model',
            name='name',
            field=models.CharField(default='Zekolns_1', max_length=15, verbose_name='mark name'),
        ),
    ]
