# Generated by Django 5.0.6 on 2024-06-04 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_car_model_owned_by_alter_car_model_family_of_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise_action',
            name='bio',
            field=models.TextField(blank=True, default='\nProvident nihil minus qui consequatur non omnis maiores. Eos accusantium minus dolores iure perferendis tempore et consequatur.\n                   \n', max_length=150, null=True, verbose_name='details'),
        ),
        migrations.AlterField(
            model_name='car_model',
            name='bio',
            field=models.TextField(blank=True, default='\nProvident nihil minus qui consequatur non omnis maiores. Eos accusantium minus dolores iure perferendis tempore et consequatur.\n                   \n', null=True, verbose_name='details'),
        ),
        migrations.AlterField(
            model_name='decorator_model',
            name='bio',
            field=models.TextField(blank=True, default='\nProvident nihil minus qui consequatur non omnis maiores. Eos accusantium minus dolores iure perferendis tempore et consequatur.\n                   \n', null=True, verbose_name='details'),
        ),
        migrations.AlterField(
            model_name='mark_model',
            name='bio',
            field=models.TextField(blank=True, default='\nProvident nihil minus qui consequatur non omnis maiores. Eos accusantium minus dolores iure perferendis tempore et consequatur.\n                   \n', null=True, verbose_name='details'),
        ),
        migrations.AlterField(
            model_name='part_model',
            name='bio',
            field=models.TextField(blank=True, default='\nProvident nihil minus qui consequatur non omnis maiores. Eos accusantium minus dolores iure perferendis tempore et consequatur.\n                   \n', null=True, verbose_name='details'),
        ),
        migrations.AlterField(
            model_name='school_of_drive',
            name='bio',
            field=models.TextField(blank=True, default='\nProvident nihil minus qui consequatur non omnis maiores. Eos accusantium minus dolores iure perferendis tempore et consequatur.\n                   \n', null=True, verbose_name='details'),
        ),
        migrations.CreateModel(
            name='Fix_action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, default='\nProvident nihil minus qui consequatur non omnis maiores. Eos accusantium minus dolores iure perferendis tempore et consequatur.\n                   \n', null=True, verbose_name='details')),
                ('owned_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_fix_x', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fix_action',
                'verbose_name_plural': 'Fix_actions',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
